### ISSUE TITLE
Cloudwatch solution (Alarms)

### ISSUE THREAD

**Issue by christina-roperto** [devopsacademyau/2020-feb-project1-group1#4]
- Alarms for Wordpress (ECS)
- Alarms for RDS
- Aplications load balance configuration

**Comment by christina-roperto** [comment]
I'm removing myself for now. Feel take this or reassign this to me later once all the resources needed are done

**Comment by denstorti** [comment]
Hi @christina-roperto ,

one important task of this issue is configuring logs for the container in order to be able to see the container logs in Clooudwatch.

As you can see in the image below, containers are not logging for now, so if an error in wordpress occurs we won't be able to see it.
![image](https://user-images.githubusercontent.com/8410423/80293991-3748e100-87a8-11ea-98a4-78f450706683.png)

Alarms are good to have, not mandatory.

**Comment by christina-roperto** [comment]
- adding log config to ECS
- alarms if RDS uses more than 70% CPU
- alarms if response time is more than 3s
