### ISSUE TITLE
Error make deploy - Invalid SMS endpoint

### ISSUE THREAD

**Issue by denstorti** [devopsacademyau/2020-feb-project1-group1#71]
Running `make deploy`: 
```
Error: Error creating SNS topic: InvalidParameter: Invalid SMS endpoint: +614xxxxxxxx
	status code: 400, request id: 3b380cd4-974c-5d24-b9ce-5bca5db28d87
```
Stacktrace:
```
  on modules/aws-cloudwatch/notification.tf line 5, in resource "aws_sns_topic_subscription" "sms":
   5: resource "aws_sns_topic_subscription" "sms" {
```
![image](https://user-images.githubusercontent.com/8410423/80293284-80e1fd80-87a1-11ea-8fee-d44e0a989d4a.png)

This should come from SSM for conditionally not create the notification if the SMS number is empty. I reckon email instead of SMS is what enterprises usually use as you can just send 1 email to a mailbox and distribute to several teams.

**Comment by christina-roperto** [comment]
Hi Denis, I'm aware of that. You need to edit your .env because your phone number is incorrect. There's another issue that the makefile is overwriting .env with .env.example everytime it runs which makes you lose your setting. Lucas is migrating this to SSM #68  so it's probably better to wait until that's done to address that issue because it's almost merged :)
